### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by karakuse** [solygambas/react-native-shopping-app#2]
after issuing command 
expo start -w

 web  Failed to compile.
D:/react-native-shopping-app/store/actions/products.js
Module not found: Can't resolve '../../constants/Environment' in 'D:\react-native-shopping-app\store\actions'

**Comment by solygambas** [comment]
you need to create the missing folder constants and the missing file Environment.js. Then add your firebase keys in this file.

**Comment by karakuse** [comment]
can you give an example of this file Environment.js?

**Comment by solygambas** [comment]
off course, I added it to the repo, check the constants folder.
